server:
  port: 8082
  contextPath: /payservice
  tomcat:
    uri-encoding: UTF-8

mysql:
  connection:
    url: jdbc:mysql://116.62.219.91:3306/fct?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: fct
    password: lf6pQJW2wguBq5hZ

pay:
  wxpay_fctwap:
    key:  40030613ae6f219923c3634e047abe4e
    mchid:  1405964802
    notifyurl:  http://pay.fangcun.com/mobile/wxpay/notify
    cert_path:  /usr/local/fct/cert/wxpay/fctwap/1405964802_cert.p12
    cert_password:  1405964802
    appid:  wx5b63ee784fa7fc96
    appsecret:  d70744148ac1f943f844caa175f8ee73

  wxpay_fctapp:
    key:  40030613ae6f219923c3634e047abe4e
    mchid:  1442883002
    notifyurl:  http://pay.fangcun.com/mobile/wxpay/appnotify
    cert_path:  /usr/local/fct/cert/wxpay/fctapp/1442883002_cert.p12
    cert_password:  1442883002
    appid:  wx7c866f046dab34b8
    appsecret:  7b6d038c11400a323bbd7f7849021159

  alipay_fctapp:
    partner:  2088621198090730
    key:  alhanc3pys7dm7o1vqdmtv5bzjj1kpvj
    selleraccount:  pay@fct.com
    notifyurl:  http://pay.fangcun.com/mobile/alipay/appnotify
    privatekey_path:  /cert/alipay/rsa_private_key.pem
    publickey_path:  /cert/alipay/rsa_public_key.pem

  unionpay_fctwap:
    meriId: 777290058148557
    frontTransUrl: https://gateway.test.95516.com/gateway/api/frontTransReq.do?
    backTransUrl: https://gateway.test.95516.com/gateway/api/backTransReq.do?
    encryptCert_path:  /usr/local/fct/cert/unionpay/fctwap/acp_test_enc.cer
    signCert_path:  /usr/local/fct/cert/unionpay/fctwap/700000000000001_acp.pfx
    signCert_pwd: 000000
    validateCert_dir: /usr/local/fct/cert/unionpay/fctwap
    backUrl:  http://pay.fangcun.com/mobile/unionpay/notify
    frontUrl: http://pay.fangcun.com/mobile/unionpay/callback
    refund_backUrl: http://pay.fangcun.com/mobile/unionpay/refundnotify

  platform_ids:
    wxpay_appids: wxpay_fctwap#wx5b63ee784fa7fc96|wxpay_fctapp#wx7c866f046dab34b8
    alipay_sellerids:  alipay_fctapp#2088621198090730
    unionpay_merids: unionpay_fctwap#777290058148557








