server:
  port: 8082
  contextPath: /payservice
  tomcat:
    uri-encoding: UTF-8

pay:
  wxpay_fctwap:
    key:  40030613ae6f219923c3634e047abe4e
    mchid:  1405964802
    notifyurl:  http://test.pay.fangcuntang.com/mobile/wxpay/notify
    cert_path:  /usr/local/cert/wxpay/fctwap/1405964802_cert.p12
    cert_password:  1405964802
    appid:  wx39f1f76373754d3c
    appsecret:  5acae7250a2c8ba316aa4fb16b1d0146

  wxpay_fctapp:
    key:  40030613ae6f219923c3634e047abe4e
    mchid:  1442883002
    notifyurl:  http://teste.pay.fangcuntang.com/mobile/wxpay/appnotify
    cert_path:  /usr/local/cert/wxpay/fctapp/1442883002_cert.p12
    cert_password:  1442883002
    appid:  wx7c866f046dab34b8
    appsecret:  7b6d038c11400a323bbd7f7849021159

  alipay_fct:
      appid:  2017072007823643
      notifyurl:  http://test.pay.fangcuntang.com/mobile/alipay/notify
      returnurl:  http://test.pay.fangcuntang.com/mobile/alipay/callback
      appnotifyurl:  http://test.pay.fangcun.com/mobile/alipay/appnotify
      privatekey_path:  /usr/local/cert/alipay/fct/private_key.txt
      publickey_path:  /usr/local/cert/alipay/fct/public_key.txt

  unionpay_fctwap:
    meriId: 777290058148557
    frontTransUrl: https://gateway.test.95516.com/gateway/api/frontTransReq.do?
    backTransUrl: https://gateway.test.95516.com/gateway/api/backTransReq.do?
    encryptCert_path:  /usr/local/cert/unionpay/fctwap/acp_test_enc.cer
    signCert_path:  /usr/local/cert/unionpay/fctwap/700000000000001_acp.pfx
    signCert_pwd: 000000
    validateCert_dir: /usr/local/cert/unionpay/fctwap
    backUrl:  http://test.pay.fangcuntang.com/mobile/unionpay/notify
    frontUrl: http://test.pay.fangcuntang.com/mobile/unionpay/callback
    refund_backUrl: http://test.pay.fangcuntang.com/mobile/unionpay/refundnotify

  platform_ids:
    wxpay_appids: wxpay_fctwap#wx5b63ee784fa7fc96|wxpay_fctapp#wx7c866f046dab34b8
    alipay_appids:  alipay_fct#2017072007823643
    unionpay_merids: unionpay_fctwap#777290058148557








