server:
  port: 8087
  contextPath: /common
  tomcat:
    uri-encoding: UTF-8

redis:
  host:
    url: 127.0.0.1
    port: 6379
    test:
      onborrow: true
    max:`                                                                                                                                                                                                                                                                                                           `
      idel: 300
      total: 300
      waitmillis: 1000

mysql:
  connection:
    url: jdbc:mysql://121.196.192.85:3306/fct?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: fct
    password: lf6pQJW2wguBq5hZ

aliyun:
  oss:
    bucketName: fct-nick
    accesskeyId: LTAId0h3QAgdPmXT
    accesskeySecret: cLMJrTzs1APvyXehfjOQUsYq66A3Wc
    endpoint: http://oss-cn-shanghai.aliyuncs.com/

oauth:
  wechat:
    appId: wx39f1f76373754d3c
    appSecret: 5acae7250a2c8ba316aa4fb16b1d0146
