server:
  port: 8090
  contextPath: /adminweb
  tomcat:
    uri-encoding: UTF-8


redis:
  host:
    url: 127.0.0.1
    port: 6379
    test:
      onborrow: true
    max:
      idel: 300
      total: 300
      waitmillis: 10000
      maxactive: 300

spring:
  http:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
    encoding:
      charset: utf-8
      enabled: true
      force: true
  thymeleaf:
    #prefix: classpath:/templates,classpath:/static/
    #suffix: .html
    cache: false
    check-template: true
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
fct:
  domain:
    url: http://www.fangcun.com
    imageurl: http://fct-nick.img-cn-shanghai.aliyuncs.com
    videourl: http://video.fangcun.com
    staticurl:

