server:
  port: 8081
  contextPath: /message
  tomcat:
    uri-encoding: UTF-8


redis:
  host:
    url: 127.0.0.1
    port: 6379
    test:
      onborrow: true
    max:
      idel: 300
      total: 300
      waitmillis: 1000

mysql:
  connection:
    url: jdbc:mysql://121.196.192.85:3306/fct?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: fct
    password: lf6pQJW2wguBq5hZ

qcloud:
  sms:
    appid: 1400034770
    appkey: b2d927f48ea8b897b373014f30d0f305


