server:
  port: 8086
  contextPath: /promotion
  tomcat:
    uri-encoding: UTF-8


redis:
  host:
    url: 127.0.0.1
    port: 6379
    test:
      onborrow: true
    max:
      idel: 300
      total: 300
      waitmillis: 1000

mysql:
  connection:
    url: jdbc:mysql://121.196.192.85:3306/fct?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: fct
    password: lf6pQJW2wguBq5hZ




